import type { Metadata } from "next";
import {
  Roboto,
  Bricolage_Grotesque,
  Alegreya_Sans,
  Poiret_One,
  Inter,
  Cormorant_Garamond,
  Source_Sans_3,
  Libre_Baskerville,
  Lato,
} from "next/font/google";
import type { EditorFontOption } from "@/lib/editorFonts";
import { getAdminUiSettings, getEnabledEditorFonts } from "@/lib/uiSettings";
import "./globals.css";

const headingFont = Source_Sans_3({
  variable: "--font-heading",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

const bodyFont = Roboto({
  variable: "--font-body",
  subsets: ["latin"],
  weight: ["400", "500", "700"],
});

const displayFont = Bricolage_Grotesque({
  variable: "--font-bricolage",
  subsets: ["latin"],
  weight: ["400", "500", "600"],
});

const alegreyaSansFont = Alegreya_Sans({
  variable: "--font-alegreya-sans",
  subsets: ["latin"],
  weight: ["400"],
  style: ["normal", "italic"],
});

const poiretFont = Poiret_One({
  variable: "--font-poiret",
  subsets: ["latin"],
  weight: ["400"],
});

const interFont = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

const cormorantFont = Cormorant_Garamond({
  variable: "--font-cormorant-garamond",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

const libreBaskervilleFont = Libre_Baskerville({
  variable: "--font-libre-baskerville",
  subsets: ["latin"],
  weight: ["400", "700"],
});

const latoFont = Lato({
  variable: "--font-lato",
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { editorFonts } = await getAdminUiSettings();
  const enabledEditorFonts = getEnabledEditorFonts(editorFonts);
  const fontsWithImports = enabledEditorFonts.filter(
    (f: EditorFontOption) =>
      typeof f.importUrl === "string" && f.importUrl.trim().length > 0,
  );

  return (
    <html lang="en">
      <head>
        {fontsWithImports.map((font: EditorFontOption, index: number) => (
          <link
            key={index}
            rel="stylesheet"
            href={font.importUrl}
          />
        ))}
      </head>
      <body
        className={`${bodyFont.variable} ${headingFont.variable} ${displayFont.variable} ${alegreyaSansFont.variable} ${poiretFont.variable} ${interFont.variable} ${cormorantFont.variable} ${libreBaskervilleFont.variable} ${latoFont.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
